<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gimbal">

  <!-- Properties -->
  <xacro:property name="pedestal_z" value="0.073" />
  <xacro:property name="pan_z" value="0.194" />
  <xacro:property name="tilt_z" value="0.211" />

  <!-- ============ GIMBAL BASE (Pedestal) ============ -->
  <link name="gimbal_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi} 0 0" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/gimbal_base.dae" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.155 0.155 0.073" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
  </link>

  <!-- ============ GIMBAL PAN (Big Box) ============ -->
  <link name="gimbal_pan_link">
    <visual>
      <!-- <origin xyz="0 0 0" rpy="${pi} 0 0"/> -->
      <origin xyz="0 0 0" rpy="${pi} 0 ${pi}" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/gimbal_pan.dae" />
      </geometry>
    </visual>
    <!-- <collision>
      <geometry>
        <box size="0.172 0.180 0.194" />
      </geometry>
    </collision> -->
    <collision>
      <geometry>
        <box size="0.15 0.15 0.15" />  <!-- Smaller -->
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8" />
      <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002" />
    </inertial>
  </link>

  <joint name="gimbal_pan_joint" type="revolute">
    <parent link="gimbal_base_link" />
    <child link="gimbal_pan_link" />
    <origin xyz="0 0 ${pedestal_z/2 + pan_z/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="${-pi}" upper="${pi}" effort="10" velocity="1.0" />
    <dynamics damping="0.5" friction="0.1" />
  </joint>

  <!-- ============ GIMBAL TILT (Head) ============ -->
  <link name="gimbal_tilt_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi} 0 0" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/gimbal_tilt.dae" />
      </geometry>
    </visual>
    <!-- <collision>
      <geometry>
        <box size="0.125 0.218 0.211" />
      </geometry>
    </collision> -->
    <collision>
      <geometry>
        <box size="0.10 0.18 0.15" />  <!-- Smaller -->
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
  </link>

  <joint name="gimbal_tilt_joint" type="revolute">
    <parent link="gimbal_pan_link" />
    <child link="gimbal_tilt_link" />
    <!-- <origin xyz="0 0 ${pan_z/2 + tilt_z/2}" rpy="0 0 0"/> -->
    <!-- <origin xyz="0 0 ${pan_z/2}" rpy="0 0 0"/> -->
    <origin xyz="0 0 0.01" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${-pi/4}" upper="${pi/4}" effort="10" velocity="1.0" />
    <dynamics damping="0.5" friction="0.1" />
  </joint>
  <!-- ============ RGB Camera Link ============ -->
  <link name="gimbal_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 -1.5708 3.1416" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/camera.dae" />
      </geometry>
    </visual>

    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/camera.dae" />
      </geometry>
    </collision> -->
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.055 0.064 0.123" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.05" />
      <inertia
        ixx="1e-4" ixy="0.0" ixz="0.0"
        iyy="1e-4" iyz="0.0"
        izz="1e-4" />
    </inertial>
  </link>
  <joint name="gimbal_camera_joint" type="fixed">
    <parent link="gimbal_tilt_link" />
    <child link="gimbal_camera_link" />
    <origin xyz="0 -0.03 ${tilt_z/2+0.025}" rpy="0 0 0" />
  </joint>
  <!-- ============ IR Camera Link ============ -->
  <link name="gimbal_ir_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 -1.5708 3.1416" />
      <geometry>
        <mesh filename="package://tin3_bot/meshes/camera.dae" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.055 0.064 0.123" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2" />
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
    </inertial>
  </link>
  <joint name="gimbal_ir_camera_joint" type="fixed">
    <parent link="gimbal_tilt_link" />
    <child link="gimbal_ir_camera_link" />
    <origin xyz="0 0.03 ${tilt_z/2+0.025}" rpy="0 0 0" />
  </joint>
</robot>